---
- name: Deploy application in Docker container
  hosts: localhost
  become: yes
  tasks:

    - name: Build Docker image
      docker_image:
        name: boxfuse-in-docker:1.0.0
        path: /root/certification_project
        state: present
        force: yes

    - name: Run Docker container
      docker_container:
        name: mywebapp-test
        image: boxfuse-in-docker:1.0.0
        ports:
          - "8080:8080"
        state: started