---
- name: Deploy application in Docker container
  hosts: build
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages for Docker
      package:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      apt:
        name: docker-ce docker-ce-cli containerd.io
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    - name: Log in to Docker Hub
      command: docker login -u "{{ docker-username }}" -p "{{ docker-password }}"

    - name: Create project directory
      file:
        path: /usr/app
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/uladzimirzel/certification_project
        dest: /usr/app

    - name: Build Docker image
      docker_image:
        name: boxfuse:1.0.0
        path: /usr/app
        state: present

    - name: Tag Docker image
      docker_image:
        name: boxfuse:1.0.0
        tag: 1.0.0
        repository: "{{ docker-username }}/boxfuse:1.0.0"

    - name: Push Docker image
      docker_image:
        name: "{{ docker-username }}/boxfuse:1.0.0"
        push: yes