---
- name: Deploy application in Docker container
  hosts: build
  become: yes
  tasks:

    - name: Create project directory
      file:
        path: /usr/app
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/uladzimirzel/certification_project
        dest: /usr/app