---
- name: Deploy application in Docker container
  hosts: build
  become: yes
  tasks:

    - name: Create project directory
      file:
        path: /usr/app
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/uladzimirzel/certification_project
        dest: /usr/app

    - name: Build Docker image
      docker_image:
        name: boxfuse:1.0.0
        path: /usr/app
        state: present

    - name: Tag Docker image
      docker_image:
        name: boxfuse:1.0.0
        tag: europe-central2-docker.pkg.dev/peppy-web-405812/my-docker/boxfuse:1.0.0
        source: local
        force_tag: yes

    - name: Push Docker image
      docker_image:
        name: europe-central2-docker.pkg.dev/peppy-web-405812/my-docker/boxfuse:1.0.0
        push: yes