---
- name: Deploy application in Docker container
  hosts: build
  become: yes
  tasks:

    - name: git clone repository
      git:
        repo: https://github.com/uladzimirzel/certification_project
        dest: /