---
- name: install maven
  hosts: {{ BUILD_INSTANCE }}
  become: true

  tasks:
    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Clone Java application repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
        dest: /opt/boxfuse-sample-java-war-hello