---
- name: Deploy application in Docker container
  hosts: build
  become: yes
  tasks:

    - name: git clone repository
      git:
        repo: https://github.com/uladzimirzel/certification_project
        dest: /opt/app

    - name: Build Docker image
      docker_image:
        name: mywebapp
        build:
          path: /opt/app
          source: build
        state: present
        force_tag: yes

    - name: Run Docker container
      docker_container:
        name: mywebapp
        image: mywebapp
        ports:
          - "8080:8080"
        state: started