---
- name: Deploy application in Docker container
  hosts: build
  become: yes
  tasks:
  
    - name: Create project directory
      file:
        path: /usr/app
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/uladzimirzel/certification_project
        dest: /usr/app

    - name: Build Docker image
      docker_image:
        name: boxfuse:1.0.0
        path: /usr/app
        state: present

    - name: Tag Docker image
      docker_image:
        name: boxfuse:1.0.0
        tag: 1.0.0
        repository: "{{ docker-username }}/boxfuse:1.0.0"

    - name: Push Docker image
      docker_image:
        name: "{{ docker-username }}/boxfuse:1.0.0"
        push: yes